### ISSUE TITLE
Feature Request - Feather Falling

### ISSUE THREAD

**Issue by raggebatman** [pcal43/footpaths#7]
Just came across this, it's really neat! If you're interested, I've got a suggestion.
I think it'd be fun (and make some sense) for Feather Falling to prevent the effect of this mod. 
A config option to enable/disable this behaviour would be welcome.
What do you think?

**Comment by pcal43** [comment]
Yeah, somebody on curseforge just asked for the same thing:
https://www.curseforge.com/minecraft/mc-mods/footpaths?comment=1

It's a good idea, shouldn't be hard to add.  A little slammed irl atm but I'll try to get to it in the next couple weeks.

**Comment by pcal43** [comment]
added in trailblazer-0.1.0
